### ISSUE TITLE
 Gerar token de acesso da twitch API

### ISSUE THREAD

**Issue by jakeliny** [dev-house-community/ThasfinBot#21]

**Comment by caio-emidio** [comment]
tem alguns pontos interessantes nessa task.
Ao gerar o token.
Voce consegue gerar token para desenvolvimento?
ou consegue gerar um token agora para testes e depois apagar e gerar outro?

Qual o risco que corremos se esse token cair em "maos erradas"?

**Comment by jakeliny** [comment]
Cada dev deve gerar seu proprio token e colocar no arquivo .env, subi o arquivo atualizado com chaves necessárias. 

Precisa ter autenticação de dois fatores na conta da twitch, entrar nesse link:  [https://dev.twitch.tv/dashboard/apps cadastrar uma aplicação e na página da aplicação gerar o TWITCH_CLIENT_ID, TWITCH_CLIENT_SECRET e cadastrar o callback como: http://localhost:3000/auth/twitch/callback

**Comment by jakeliny** [comment]
@dev-house-community/newpromise criem as suas chaves e coloquem em uma .env como o modelo .env.development
