### ISSUE TITLE
Comandos separados dinamicamente por live

### ISSUE THREAD

**Issue by jakeliny** [dev-house-community/ThasfinBot#23]
Add verificação de onde vem comando e retornar mensagem equivalente Exemplo: !instagram retornar o instagram da jake se vier da live da jake ou retornar o instagram do mayk caso esteja na live do mayk

**Comment by jakeliny** [comment]
Geo abriu PR para essa feature: https://github.com/dev-house-community/ThasfinBot/pull/10

**Comment by caio-emidio** [comment]
@jakeliny apenas para seu conhecimento. Voce consegue linkar o PR com issues a partir do "Linekd Pull Requests" que fica no menu aqui da direita.

**Comment by jakeliny** [comment]
Código feito pelo Geo foi mergiado para dev!

**Comment by jakeliny** [comment]
Aguardando teste em live...
